import {describe,it,expect} from 'vitest';
import {Readable} from 'node:stream';
import {scryptSync} from 'node:crypto';
import {createReviewMiddleware} from '../../../tooling/houki/dev-review.mjs';
const accounts=[{name:'reviewer',salt:'salt',hash:scryptSync('secret','salt',32).toString('hex'),roles:['houki-review']},{name:'observer',salt:'salt',hash:scryptSync('secret','salt',32).toString('hex'),roles:[]}];
function harness(production=false){let loads=0;const run=createReviewMiddleware({accounts,production,loadData:async()=>{loads++;return {fixture:'private-fixture'};}});return {loads:()=>loads,request:async(url:string,method='GET',body='',headers:Record<string,string>={},remote='127.0.0.1')=>{const req=Object.assign(Readable.from(body?[body]:[]),{url,method,headers:{host:'127.0.0.1:5187',...headers},socket:{remoteAddress:remote}});const result={status:0,headers:{} as Record<string,string>,body:'',next:false};const res={setHeader:(k:string,v:string)=>result.headers[k]=v,writeHead:(s:number,h:Record<string,string>={})=>{result.status=s;Object.assign(result.headers,h);},end:(s='')=>result.body=String(s)};await run(req,res,()=>result.next=true);return result;}};}
describe('dev review server authorization boundary',()=>{
 it('never loads a private record before authentication',async()=>{const h=harness();expect((await h.request('/__houki-review/data')).status).toBe(401);expect(h.loads()).toBe(0);});
 it('authenticates observers but denies reviewer permission',async()=>{const h=harness();const login=await h.request('/__houki-review/login','POST','name=observer&password=secret');expect(login.status).toBe(303);expect((await h.request('/__houki-review/data','GET','',{cookie:login.headers['Set-Cookie']})).status).toBe(403);expect(h.loads()).toBe(0);});
 it('permits a reviewer and revokes logout',async()=>{const h=harness();const login=await h.request('/__houki-review/login','POST','name=reviewer&password=secret');const cookie=login.headers['Set-Cookie'];expect(cookie).toContain('HttpOnly; SameSite=Strict');const data=await h.request('/__houki-review/data','GET','',{cookie});expect(data.status).toBe(200);expect(data.headers['Cache-Control']).toBe('no-store');await h.request('/__houki-review/logout','POST','',{cookie});expect((await h.request('/__houki-review/data','GET','',{cookie})).status).toBe(401);});
 it('denies LAN, cross-origin, forged session and production',async()=>{const h=harness();for(const [headers,remote] of [[{host:'192.168.1.2:5187'},'192.168.1.3'],[{origin:'https://example.org'},'127.0.0.1'],[{'sec-fetch-site':'cross-site'},'127.0.0.1']] as const){expect((await h.request('/__houki-review/data','GET','',headers as Record<string,string>,remote)).status).toBe(403);}expect((await h.request('/__houki-review/data','GET','',{cookie:'cwotHoukiReviewer=forged'})).status).toBe(401);expect((await harness(true).request('/__houki-review/login')).status).toBe(403);expect(h.loads()).toBe(0);});
 it('blocks file-server bypass including encoded paths',async()=>{const h=harness();for(const p of ['/docs/1sou_houki/private/x','/@fs/a/docs/x','/@fs/a/%64ocs/x','/data/x.authoring.json','/.git/config','/.env.local'])expect((await h.request(p)).status).toBe(404);expect((await h.request('/app/houki')).next).toBe(true);});
 it('never includes failures or private data in an error response',async()=>{const h=harness();const fail=await h.request('/__houki-review/login','POST','name=reviewer&password=wrong');expect(fail.status).toBe(403);expect(fail.body).not.toContain('private-fixture');});
});
