import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {validateRelease,generateRelease} from './release-validator.mjs';
import {LessonPlayer,RedSheetPlayer} from '../../../app/components/houki/LessonPlayer';
import {loadLessonRelease} from './lesson-loader';
import {decodeSheetReturn,encodeSheetReturn,restoredPositions} from './return-state';
import {readLocation,questionOrder,toggleRevealed} from './engine';
const original=JSON.parse(readFileSync('data/houki/original-samples.authoring.json','utf8'));
const dto=validateRelease(JSON.parse(readFileSync('public/houki/trainer/lessons-v1.json','utf8')));
describe('JSON lessons / independent release gates',()=>{
 it('strict Draft07 schema, migration counts and generated DTO match',()=>{expect(generateRelease(original)).toEqual(dto);expect(dto.lessons).toHaveLength(2);expect(dto.master.questions).toHaveLength(3);expect(new Set(dto.lessons.flatMap(l=>l.blocks.map(b=>b.type))).size).toBe(10);});
 it('rejects unknown schema/type, missing fields, private fields and invalid references',()=>{
 const mutations=[(x:any)=>x.schemaVersion='2.0.0',(x:any)=>x.lessons[0].blocks[0].type='execute',(x:any)=>delete x.lessons[0].title,(x:any)=>x.lessons[0].blocks[0].pointer='/private',(x:any)=>x.lessons[0].blocks.push(x.lessons[0].blocks[0]),(x:any)=>x.lessons[0].questionIds=['missing'],(x:any)=>x.lessons[0].contentVersion=2,(x:any)=>x.master.questions[0].tokens.push(x.master.questions[0].tokens[1]),(x:any)=>x.master.questions[0].blanks[1].printedPositionId=x.master.questions[0].blanks[0].printedPositionId,(x:any)=>x.master.rules[0].conditionIds=['missing']];
 for(const change of mutations){const x=structuredClone(dto);change(x);expect(()=>validateRelease(x)).toThrow();}
 });
 it('parent approval cannot publish an unapproved block/child/source/blank',()=>{for(const purpose of ['sample:block:keyPoints','sample:questions','sample:sources','sample:blank','sample:amendments']){const x=structuredClone(original);x.payload.publicReviews.find((r:any)=>r.purpose===purpose).rights='pending';expect(()=>generateRelease(x)).toThrow();}});
 it('human/legal approval cannot be inferred from sample or verified state',()=>{const x=structuredClone(original);x.payload.master.edition='approved_release';expect(()=>generateRelease(x)).toThrow();const y=structuredClone(original);y.payload.publicReviews[0].approvedAt='yesterday';expect(()=>generateRelease(y)).toThrow();});
 it('intentional question↔lesson backlink accepted, composition cycle rejected',()=>{expect(validateRelease(dto)).toBe(dto);const x=structuredClone(dto);x.lessons[0].prerequisiteLessonIds=[x.lessons[1].id];x.lessons[1].prerequisiteLessonIds=[x.lessons[0].id];expect(()=>validateRelease(x)).toThrow(/循環/);});
 it('strips private authoring evidence; nested unknowns are refused rather than copied',()=>{const x=structuredClone(original);x.privateEvidence.secret='never-publish';expect(JSON.stringify(generateRelease(x))).not.toContain('never-publish');x.payload.master.sources[0].sourceHash='secret';expect(()=>generateRelease(x)).toThrow();});
 it('renders all 10 block types in JSON order with escaped text and shared problem explanation',()=>{
 const html=dto.lessons.map(l=>renderToStaticMarkup(createElement(LessonPlayer,{release:dto,lessonId:l.id,openQuestion:()=>{}}))).join('');for(const type of ['explanation','keyPoints','conditions','procedure','comparison','question','redSheet','amendment','pitfall','source'])expect(html).toContain(`data-block-type="${type}"`);
 const x=structuredClone(dto);const b=x.lessons[0].blocks.find(b=>b.type==='explanation')!;if(b.type==='explanation')b.body='<script>alert(1)</script>';const safe=renderToStaticMarkup(createElement(LessonPlayer,{release:x,lessonId:x.lessons[0].id,openQuestion:()=>{}}));expect(safe).toContain('&lt;script&gt;');expect(safe).not.toContain('<script>');
 const order=x.lessons[0].blocks.map(b=>safe.indexOf(`data-block-type="${b.type}"`));expect(order).toEqual([...order].sort((a,b)=>a-b));
 });
 it('shared red sheet hides answers, reveals individual/all, keeps explanation paired',()=>{const q=dto.master.questions[0];const draw=(ids:string[])=>renderToStaticMarkup(createElement(RedSheetPlayer,{question:q,revealed:ids,setRevealed:()=>{},explanationOpen:false,setExplanationOpen:()=>{}}));expect(draw([])).toContain('aria-expanded="false"');const ids=q.blanks.map(b=>b.printedPositionId);expect(draw(ids)).toContain('aria-expanded="true"');expect(draw(ids)).toContain(q.explanation);expect(toggleRevealed(ids,ids[0])).toEqual([ids[1]]);});
 it('sheet→book→sheet snapshot preserves seed/filter/question/version/reveal/explanation',()=>{const q=dto.master.questions[0];const location=readLocation('?mode=sheet&question='+q.id+'&year=2026&chapter=sample-delivery&random=1&seed=19');const state={location,questionVersion:q.version,revealed:[q.blanks[0].printedPositionId],explanationOpen:true};const restored=decodeSheetReturn(encodeSheetReturn(state))!;expect(restored).toEqual(state);expect(restoredPositions(restored,q)).toEqual(state.revealed);expect(questionOrder(dto.master.questions,location.year,location.chapter,true,19)).toEqual(questionOrder(dto.master.questions,restored.location.year,restored.location.chapter,true,restored.location.seed));expect(restoredPositions(restored,{...q,version:2})).toEqual([]);expect(decodeSheetReturn('{bad')).toBeNull();expect(decodeSheetReturn(JSON.stringify({...state,location:{mode:'book'}}))).toBeNull();});
 it('version index loads safely and malformed releases fail before rendering',async()=>{const originalFetch=globalThis.fetch;const silence=vi.spyOn(console,'error').mockImplementation(()=>{});try{globalThis.fetch=async(url)=>url==='/houki/trainer/active.json'?Response.json({schemaVersion:'1.0.0',contentVersion:1,file:'/houki/trainer/lessons-v1.json'}):Response.json(dto);expect(await loadLessonRelease()).toEqual(dto);globalThis.fetch=async()=>Response.json({schemaVersion:'1.0.0',contentVersion:1,file:'https://example.com/data.json'});await expect(loadLessonRelease()).rejects.toThrow('形式');globalThis.fetch=async(url)=>url==='/houki/trainer/active.json'?Response.json({schemaVersion:'1.0.0',contentVersion:1,file:'/houki/trainer/lessons-v1.json'}):Response.json({...dto,schemaVersion:'unknown'});await expect(loadLessonRelease()).rejects.toThrow('形式');}finally{globalThis.fetch=originalFetch;silence.mockRestore();}});
 it('safe missing lesson and invalid loader fail without showing content',()=>{expect(renderToStaticMarkup(createElement(LessonPlayer,{release:dto,lessonId:'missing',openQuestion:()=>{}}))).toContain('role="alert"');});
});
