import {describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
import {generateRelease,validateRelease,validateReviewPreview} from './release-validator.mjs';
import {allowedRequest,createReviewServer} from '../../../docs/1sou_houki/StageK4-F/preview/serve.mjs';
function fixture(){const x=generateRelease(JSON.parse(readFileSync('data/houki/original-samples.authoring.json','utf8')));x.master.edition='internal_review';for(const n of x.master.notes){n.effectiveStatus='verified';n.publicEligibility='needs_context';}for(const q of x.master.questions){q.provenance='original_practice';q.sampleYear=null;}for(const r of x.master.reviews){r.humanApproval='pending';r.rights='pending';r.purpose=x.master.questions.some(q=>q.id===r.contentRef.id)?'original_practice':x.master.cards.some(c=>c.id===r.contentRef.id&&c.kind==='amendment')?'amendment':'current_note';}for(const r of x.publicReviews){r.purpose=r.purpose.replace('sample:','release:');r.humanApproval='pending';r.rights='pending';}return x;}
describe('local review channel never grants a release',()=>{
 it('validates structure of pending content without mutating approvals',()=>{const x=fixture();expect(validateReviewPreview(x)).toBe(x);expect(x.publicReviews.every(r=>!r.releaseApproved&&r.approvedAt===null)).toBe(true);expect(()=>validateRelease(x)).toThrow();});
 it('refuses missing child, invalid positions, mixed approval and private evidence',()=>{for(const change of [(x:any)=>x.lessons[0].questionIds=['missing'],(x:any)=>x.master.questions[0].tokens.splice(1,1),(x:any)=>x.publicReviews[0].releaseApproved=true,(x:any)=>x.master.sources[0].pointer='secret']){const x=fixture();change(x);expect(()=>validateReviewPreview(x)).toThrow();}});
 it('checks loopback host/origin and denies cross-site browsers',()=>{const req=(host:string,origin?:string,site?:string)=>({headers:{host,origin,'sec-fetch-site':site}});expect(allowedRequest(req('127.0.0.1:5189'),5189)).toBe(true);expect(allowedRequest(req('evil.example:5189'),5189)).toBe(false);expect(allowedRequest(req('127.0.0.1:5189','https://evil.example'),5189)).toBe(false);expect(allowedRequest(req('127.0.0.1:5189',undefined,'cross-site'),5189)).toBe(false);});
 it('server authenticates every content route, limits paths and adds no-store',()=>{const token='test-local-review-session';const server=createReviewServer({data:{marker:'review-only'},bundle:'safe-js',css:'safe-css',token});const request=(url:string,cookie?:string,method='GET')=>{const result:{status:number;body:string;headers:Record<string,string>}={status:0,body:'',headers:{}};const res={setHeader:(k:string,v:string)=>{result.headers[k]=v;},writeHead:(status:number,headers?:Record<string,string>)=>{result.status=status;Object.assign(result.headers,headers);},end:(body?:string)=>{result.body=body??'';}};server.emit('request',{url,method,headers:{host:'127.0.0.1:5189',cookie}},res);return result;};
 expect(request('/review-data').status).toBe(403);const opened=request('/open?token='+token);expect(opened.status).toBe(303);expect(opened.headers['Set-Cookie']).toContain('HttpOnly; SameSite=Strict');expect(request('/review-data','cwotReview='+token).body).toContain('review-only');expect(request('/review-data','cwotReview='+token).headers['Cache-Control']).toBe('no-store');expect(request('/private/false-alert.authoring.json','cwotReview='+token).status).toBe(404);expect(request('/review-data','cwotReview='+token,'POST').status).toBe(403);expect(request('/open?token=wrong').status).toBe(403);server.close();});
 it('production environment refuses even the standalone server factory',()=>{vi.stubEnv('NODE_ENV','production');try{expect(()=>createReviewServer({data:{},bundle:'',css:'',token:'test'})).toThrow('local development');}finally{vi.unstubAllEnvs();}});
});
