// Stage 11 analysis only: immutable Stage 10 data, no new identity, score or prediction.
export const RULE_VERSION='jp-learning-compression-v1';
export const NS=[10,20,30,40,45,50,55,60,65,70,75,80,90,100,110,120,'all'];
export const METHODS={correct:'正答頻度',choice:'選択肢頻度（正誤不問）',session:'試験期登場頻度',recency:'最近重視の選択肢頻度',combined:'正答＋選択肢の等分配',diversified:'選択肢頻度＋緯度帯の保険'};
export const POLICY={rule_version:RULE_VERSION,ns:NS,methods:METHODS,history_threshold:10,history_sensitivity:[5,15],history_reason:'10 prior Japanese exam dates (~5 nominal years); fixed before results, independent of coverage/N/candidate count.',recency_half_life_exam_sessions:10,combined_weights:{correct:.5,choice:.5},tie_break:'stable learning group ID only; no future all-period tie-break',diversification:'Reserve the top 2 past-ranked groups in each of 4 verified-latitude bands plus the unknown bucket, then fill with overall past choice rank. No extra slots and no new geography inference.',band_boundaries:[31,35,39],evaluation:'Confirmed correct appearances C/E; distinct correct group coverage separately. Not score/pass.',primary_cohorts:['all','mature'],secondary_cohort:'warm',quantile:'linear interpolation on sorted fold rates',variance:'population variance of fold rates; not confidence intervals',hypothesis:'No scalar definition of stability; show mean, median, Q1, min, >=70 ratio and worst5. No post-result tuning.'};
export function quantile(xs,p){const a=[...xs].sort((x,y)=>x-y);if(!a.length)return null;const i=(a.length-1)*p,k=Math.floor(i);return a[k]+(a[Math.min(k+1,a.length-1)]-a[k])*(i-k);}
export function describe(xs){const a=xs.filter(x=>x!==null&&Number.isFinite(x));if(!a.length)return {n:0,mean:null,median:null,min:null,max:null,q1:null,variance:null,stddev:null,ge50:null,ge60:null,ge70:null,ge80:null};const mean=a.reduce((s,x)=>s+x,0)/a.length,variance=a.reduce((s,x)=>s+(x-mean)**2,0)/a.length;return {n:a.length,mean,median:quantile(a,.5),min:Math.min(...a),max:Math.max(...a),q1:quantile(a,.25),variance,stddev:Math.sqrt(variance),...Object.fromEntries([50,60,70,80].map(t=>['ge'+t,a.filter(x=>x>=t/100).length/a.length]))};}
export function prepare(db,overlay,groups,learning){
 const entities=new Map(db.entities.map(e=>[e.id,e])),locations=new Map(db.locations.map(l=>[l.entity_id,l])),profiles=new Map(learning.profiles.map(p=>[p.entity_id,p]));
 const gs=groups.groups.filter(g=>g.region_id==='japan'),owner=new Map();for(const g of gs)for(const id of g.canonical_entity_ids){if(owner.has(id)||entities.get(id)?.role!=='exam_candidate'||entities.get(id)?.region_id!=='japan')throw Error('Ambiguous learning group');owner.set(id,g.id);}
 const choice=new Map(db.choices.map(c=>[c.id,c])),questions=new Map(db.questions.filter(q=>q.region_id==='japan').map(q=>[q.id,q])),sources=new Set(overlay.sources.filter(s=>s.verification_status==='verified').map(s=>s.exam_id+'|'+s.source_id)),keys=new Map(overlay.answer_keys.filter(k=>k.confidence==='verified'&&k.verification_status==='verified'&&sources.has(k.exam_id+'|'+k.source_id)).map(k=>[k.question_id,k]));
 const seen=new Set(),occ=[];for(const o of db.occurrences){if(o.confidence!=='verified'||o.evidence_status!=='image_reviewed'||!owner.has(o.entity_id)||!questions.has(o.question_id))continue;const c=choice.get(o.choice_id),q=questions.get(o.question_id);if(!c||c.entity_id!==o.entity_id||q.exam_id!==o.exam_id||c.question_id!==q.id)throw Error('Appearance join mismatch');const unique=o.choice_id+'|'+o.entity_id;if(seen.has(unique))continue;seen.add(unique);const key=keys.get(q.id),correct=key?.exam_id===o.exam_id&&key.correct_choice===c.choice_number;occ.push({...o,group_id:owner.get(o.entity_id),correct,answer_key_available:!!key});}
 const verified=new Map(occ.map(o=>[o.choice_id,o])),exams=[...db.exams].filter(e=>e.regions.includes('japan')).sort((a,b)=>a.exam_month.localeCompare(b.exam_month)||a.id.localeCompare(b.id));
 const answers=[...questions.values()].map(q=>{const key=keys.get(q.id),c=key&&key.exam_id===q.exam_id?[...choice.values()].find(c=>c.question_id===q.id&&c.choice_number===key.correct_choice):null,o=c?verified.get(c.id):null;return {question_id:q.id,exam_id:q.exam_id,key_available:!!key,correct_choice:key?.correct_choice??null,correct_choice_id:c?.id??null,canonical_entity_id:o?.entity_id??null,group_id:o?.group_id??null,capability:o?profiles.get(o.entity_id)?.capability:null,verification_status:o?'verified':'unknown',answer_source_id:key?.source_id??null};});
 const bandOf=id=>{const l=locations.get(id);if(l?.coordinate_status!=='verified'||!Number.isFinite(l.lat)||!Number.isFinite(l.lon))return 'unknown';return l.lat<31?'south':l.lat<35?'mid_south':l.lat<39?'mid_north':'north';};
 const bands=new Map(gs.map(g=>{const bs=[...new Set(g.canonical_entity_ids.map(bandOf))];return [g.id,bs.length===1?bs[0]:'unknown'];}));
 return {db,gs,entities,locations,profiles,questions,keys,owner,occ,answers,exams,bands};
}
export function trainingExams(ctx,target,period='all',from='',to=''){let ex=ctx.exams.filter(e=>e.exam_month<target.exam_month);if(period==='5'||period==='10')ex=ex.slice(-Number(period));else if(period==='custom')ex=ex.filter(e=>(!from||e.exam_month>=from)&&(!to||e.exam_month<=to));return ex;}
export function frequencies(ctx,exams){const ids=new Set(exams.map(e=>e.id)),dates=new Map(ctx.exams.map(e=>[e.id,e.exam_month])),order=new Map(exams.map((e,i)=>[e.id,i])),stats=new Map(ctx.gs.map(g=>[g.id,{group_id:g.id,choice:0,correct:0,distractor:0,session:0,correct_sessions:0,recency:0,first:null,last:null,exam_ids:[],correct_question_ids:[],choice_ids:[]}])) ;
 for(const o of ctx.occ){if(!ids.has(o.exam_id))continue;const s=stats.get(o.group_id);s.choice++;if(o.correct){s.correct++;s.correct_question_ids.push(o.question_id);}else if(o.answer_key_available)s.distractor++;s.recency+=2**(-(exams.length-1-order.get(o.exam_id))/POLICY.recency_half_life_exam_sessions);s.exam_ids.push(o.exam_id);s.choice_ids.push(o.choice_id);const date=dates.get(o.exam_id);if(!s.first||date<s.first)s.first=date;if(!s.last||date>s.last)s.last=date;}
 for(const s of stats.values()){s.exam_ids=[...new Set(s.exam_ids)];s.session=s.exam_ids.length;s.correct_question_ids=[...new Set(s.correct_question_ids)];s.correct_sessions=new Set(s.correct_question_ids.map(q=>ctx.questions.get(q).exam_id)).size;}
 return stats;
}
export function ranking(ctx,stats,method){if(!METHODS[method])throw Error('Unknown ranking');const xs=[...stats.values()].filter(s=>s.choice>0),C=xs.reduce((a,s)=>a+s.correct,0),A=xs.reduce((a,s)=>a+s.choice,0);return xs.map(s=>({group_id:s.group_id,canonical_entity_ids:ctx.gs.find(g=>g.id===s.group_id).canonical_entity_ids,score:method==='combined'?.5*(C?s.correct/C:0)+.5*(A?s.choice/A:0):s[method==='diversified'?'choice':method],correct:s.correct,choice:s.choice,session:s.session,band:ctx.bands.get(s.group_id)})).sort((a,b)=>b.score-a.score||a.group_id.localeCompare(b.group_id,'en'));}
export function selectSet(rank,N,method){const size=N==='all'?rank.length:Math.min(N,rank.length);if(!Number.isInteger(size)||size<0)throw Error('N invalid');if(method!=='diversified'||N==='all')return rank.slice(0,size);const reserve=[];for(const b of ['south','mid_south','mid_north','north','unknown'])reserve.push(...rank.filter(r=>r.band===b).slice(0,2));reserve.sort((a,b)=>rank.indexOf(a)-rank.indexOf(b));const ids=new Set(reserve.slice(0,size).map(r=>r.group_id));for(const r of rank){if(ids.size>=size)break;ids.add(r.group_id);}return rank.filter(r=>ids.has(r.group_id));}
export function distribution(selected){return Object.fromEntries(['south','mid_south','mid_north','north','unknown'].map(b=>[b,selected.filter(r=>r.band===b).length]));}
export function evaluate(ctx,selected,examIds){const ids=new Set(selected.map(r=>r.group_id)),ex=new Set(examIds),answers=ctx.answers.filter(a=>ex.has(a.exam_id)),e=answers.filter(a=>a.group_id),covered=e.filter(a=>ids.has(a.group_id)),unique=new Set(e.map(a=>a.group_id)),seenCorrect=new Set(covered.map(a=>a.group_id)),occ=ctx.occ.filter(o=>ex.has(o.exam_id)),K=answers.filter(a=>a.key_available).length,E=e.length,C=covered.length,examEligible=new Set(e.map(a=>a.exam_id)),hitExams=new Set(covered.map(a=>a.exam_id)),position=covered.filter(a=>['point','area'].includes(a.capability)).length;
 return {key_count:K,evaluable_correct_count:E,covered_correct_count:C,unknown_correct_count:K-E,correct_appearance_coverage:E?C/E:null,distinct_correct_entity_coverage:unique.size?seenCorrect.size/unique.size:null,distinct_correct_group_count:unique.size,covered_distinct_correct_group_count:seenCorrect.size,choice_appearance_coverage:occ.length?occ.filter(o=>ids.has(o.group_id)).length/occ.length:null,choice_appearance_denominator:occ.length,exam_session_any_correct_coverage:examEligible.size?hitExams.size/examEligible.size:null,exam_session_coverage_definition:'At least one confirmed correct appearance covered, not whole-session coverage.',confirmed_fraction_all_keys:K?C/K:null,position_supported_proxy_fraction:K?position/K:null,question_rows:answers.map(a=>({...a,covered:a.group_id?ids.has(a.group_id):null}))};
}
export function summarize(folds,method,N,cohort,threshold=10){const xs=folds.filter(f=>cohort==='all'||cohort==='warm'&&f.prior_exam_count>0||cohort==='mature'&&f.prior_exam_count>=threshold),rows=xs.map(f=>({exam_id:f.exam_id,prior_exam_count:f.prior_exam_count,...f.results[method][String(N)]})),valid=rows.filter(r=>r.correct_appearance_coverage!==null);return {fold_count:rows.length,evaluable_folds:valid.length,coverage:describe(rows.map(r=>r.correct_appearance_coverage)),distinct_correct_entity_coverage:describe(rows.map(r=>r.distinct_correct_entity_coverage)),effective_target_count:describe(rows.map(r=>r.entity_count)),choice_coverage:describe(rows.map(r=>r.choice_appearance_coverage)),all_key_confirmed_fraction:describe(rows.map(r=>r.confirmed_fraction_all_keys)),position_proxy:describe(rows.map(r=>r.position_supported_proxy_fraction)),worst5:[...valid].sort((a,b)=>a.correct_appearance_coverage-b.correct_appearance_coverage||a.exam_id.localeCompare(b.exam_id)).slice(0,5).map(r=>({exam_id:r.exam_id,coverage:r.correct_appearance_coverage,E:r.evaluable_correct_count,C:r.covered_correct_count,unknown:r.unknown_correct_count,entity_count:r.entity_count,prior_exam_count:r.prior_exam_count})),pooled_correct_appearance_coverage:valid.reduce((a,r)=>a+r.evaluable_correct_count,0)?valid.reduce((a,r)=>a+r.covered_correct_count,0)/valid.reduce((a,r)=>a+r.evaluable_correct_count,0):null};}
export function walkForward(ctx,{period='all',from='',to=''}={}){return ctx.exams.map(target=>{const past=ctx.exams.filter(e=>e.exam_month<target.exam_month),train=trainingExams(ctx,target,period,from,to),stats=frequencies(ctx,train),rankings=Object.fromEntries(Object.keys(METHODS).map(m=>[m,ranking(ctx,stats,m)])),results={};for(const m of Object.keys(METHODS)){results[m]={};for(const N of NS){const selected=selectSet(rankings[m],N,m),metric=evaluate(ctx,selected,[target.id]);results[m][String(N)]={entity_count:selected.length,requested_N:N,selected_group_ids:selected.map(r=>r.group_id),area_distribution:distribution(selected),...metric};}}return {exam_id:target.id,exam_month:target.exam_month,prior_exam_count:past.length,training_exam_ids:train.map(e=>e.id),eligible_group_count:rankings.choice.length,rankings,results};});}
export function classification(ctx,periodExams){const all=frequencies(ctx,ctx.exams),by=Object.fromEntries(Object.entries(periodExams).map(([p,ex])=>[p,frequencies(ctx,ex)]));return ctx.gs.map(g=>{const s=all.get(g.id),es=g.canonical_entity_ids.map(id=>ctx.entities.get(id)),obs=ctx.db.facility_observations.filter(o=>g.canonical_entity_ids.includes(o.entity_id));return {group_id:g.id,name:g.display_name,canonical_entity_ids:g.canonical_entity_ids,entity_types:[...new Set(es.map(e=>e.entity_type))],first:s.first,last:s.last,choice_appearance_count:s.choice,correct_answer_appearance_count:s.correct,distractor_appearance_count:s.distractor,exam_session_appearance_count:s.session,period_frequencies:Object.fromEntries(Object.entries(by).map(([p,map])=>{const x=map.get(g.id);return [p,{choice:x.choice,correct:x.correct,distractor:x.distractor,session:x.session}];})),confirmed_correct_evidence:s.correct_question_ids.map(id=>ctx.answers.find(a=>a.question_id===id)),coordinate_confidence:g.canonical_entity_ids.map(id=>({entity_id:id,status:ctx.locations.get(id)?.coordinate_status,confidence:ctx.locations.get(id)?.coordinate_confidence??null,source_id:ctx.locations.get(id)?.source_id,capability:ctx.profiles.get(id)?.capability})),facility_observations:obs,area_band:ctx.bands.get(g.id),classification:{A_correct_experienced:s.correct>0,B_distractor_only:s.correct===0&&s.distractor>0,C_historical_only_confirmed:false,historical_identity_required:es.some(e=>e.entity_type==='station'),D_existing_multi_entity_group:g.canonical_entity_ids.length>1,E_low_observed_evidence:s.correct===0&&s.choice<=2},learning_relevance:s.correct?'confirmed correct experience':s.distractor?'past distractor; future correct possible':'insufficient appearance evidence',low_priority_rule:'E only a descriptive all-period flag (0 correct and <=2 verified choices); never used as a future ranking feature',merge_status:g.grouping_status,merge_evidence:g.merge_evidence};});}
