export const KEY='cw-geography-progress-v1', VERSION=1;
const accepted=g=>['correct','sufficient'].includes(g);
export const empty=()=>({schemaVersion:VERSION,entities:{},recent:[],last:null,active:null,completed:[]});
export function validate(x){
 if(!x||x.schemaVersion!==VERSION||!x.entities||typeof x.entities!=='object'||Array.isArray(x.entities))throw Error('保存形式が異なります');
 const out=empty();out.entities=Object.create(null);
 for(const [id,e] of Object.entries(x.entities)){if(!id||['__proto__','constructor','prototype'].includes(id)||id.length>200||!e||!['attempts','correct','incorrect','sessionCount'].every(k=>Number.isSafeInteger(e[k])&&e[k]>=0)||e.correct+e.incorrect!==e.attempts||typeof e.lastPracticedAt!=='string'||!Number.isFinite(Date.parse(e.lastPracticedAt))||!['correct','sufficient','near','incorrect','revealed','skipped'].includes(e.recentResult)||typeof e.area!=='string'||!['A','AB','ABC','ALL'].includes(e.scope)||!['name','position'].includes(e.mode))throw Error('履歴が破損しています');out.entities[id]={...e};}
 if(!Array.isArray(x.recent)||!Array.isArray(x.completed))throw Error('履歴が破損しています');
 for(const r of x.recent){if(!r||typeof r.learningEntityId!=='string'||typeof r.area!=='string'||typeof r.at!=='string'||!Number.isFinite(Date.parse(r.at))||!['correct','sufficient','near','incorrect','revealed','skipped'].includes(r.grade))throw Error('回答履歴が破損しています');}
 if(!x.completed.every(r=>r&&typeof r.area==='string'&&typeof r.sessionID==='string'&&Number.isSafeInteger(r.total)&&r.total>=0))throw Error('完了履歴が破損しています');out.recent=x.recent.slice(-200);out.completed=x.completed.slice(-20);out.last=x.last&&typeof x.last==='object'&&!Array.isArray(x.last)&&typeof x.last.area==='string'&&['A','AB','ABC','ALL'].includes(x.last.scope)&&['name','position'].includes(x.last.direction)&&['10','20','all'].includes(x.last.size)?x.last:null;out.active=x.active&&typeof x.active==='object'?x.active:null;return out;
}
export function openStore(storage){let data=empty(),warning='',writable=true;try{const raw=storage.getItem(KEY);if(raw)data=validate(JSON.parse(raw));}catch(e){warning='保存履歴を読み込めないため、この画面内だけで練習します。元の保存データは変更しません。';writable=false;}
 return {get data(){return data;},get warning(){return warning;},get writable(){return writable;},save(){if(!writable)return;try{storage.setItem(KEY,JSON.stringify(data));}catch(e){writable=false;warning='端末に保存できません。この画面を閉じると今回の履歴は失われます。';}},replace(x){data=validate(x);writable=true;this.save();},reset(area){if(area){for(const [id,e] of Object.entries(data.entities))if(e.area===area)delete data.entities[id];data.recent=data.recent.filter(e=>e.area!==area);data.completed=data.completed.filter(e=>e.area!==area);if(data.active?.snapshot?.area===area)data.active=null;if(data.last?.area===area)data.last=null;}else data=empty();writable=true;this.save();}};
}
export function status(e){return !e?.attempts?'未練習':accepted(e.recentResult)?'最近正解':'練習中';}
export function choose(pool,data,size='10',weak=false){const xs=[...new Map(pool.map(e=>[e.learningEntityId,e])).values()].filter(e=>!weak||data.entities[e.learningEntityId]?.attempts&&!accepted(data.entities[e.learningEntityId].recentResult));xs.sort((a,b)=>{const x=data.entities[a.learningEntityId],y=data.entities[b.learningEntityId];return Number(!!x?.attempts)-Number(!!y?.attempts)||(x?.lastPracticedAt??'').localeCompare(y?.lastPracticedAt??'')||(a.areaRank??0)-(b.areaRank??0);});return size==='all'?xs:xs.slice(0,Number(size));}
export function record(data,id,grade,meta,sessionID,at=new Date().toISOString()){const e=Object.hasOwn(data.entities,id)?data.entities[id]:{attempts:0,correct:0,incorrect:0,sessionCount:0};e.attempts++;e[accepted(grade)?'correct':'incorrect']++;if(e.lastSessionId!==sessionID)e.sessionCount++;Object.assign(e,meta,{lastPracticedAt:at,recentResult:grade,lastSessionId:sessionID});data.entities[id]=e;data.recent.push({learningEntityId:id,grade,...meta,at});data.recent=data.recent.slice(-200);}
export function result(session){const first=new Map(),later=new Set();for(const r of session.results){if(!first.has(r.entity_id))first.set(r.entity_id,r.grade);else if(accepted(r.grade)&&!accepted(first.get(r.entity_id)))later.add(r.entity_id);}return {firstCorrect:[...first.values()].filter(accepted).length,firstWrong:[...first.values()].filter(g=>!accepted(g)).length,corrected:later.size,answered:first.size,total:session.eligible.length,wrongIDs:[...first].filter(([id,g])=>!accepted(g)).map(([id])=>id)};}
export function validActive(a,master){try{if(!a?.session||!a.snapshot||!Array.isArray(a.session.eligible)||!Array.isArray(a.session.fresh)||!Array.isArray(a.session.retries)||!Array.isArray(a.session.results))return false;if(typeof a.sessionID!=='string'||!Number.isSafeInteger(a.session.step)||a.session.step<0||!Number.isFinite(a.session.lastRetryStep)||!a.session.results.every(r=>r&&a.session.eligible.includes(r.entity_id)&&['correct','sufficient','near','incorrect','revealed','skipped'].includes(r.grade)))return false;const ids=new Set(master.entities.filter(e=>e.learningReady&&e.coordinateConfidence==='verified_source_representative'&&Number.isFinite(e.lat)&&Number.isFinite(e.lon)).map(e=>e.learningEntityId));if(!a.session.eligible.length||new Set(a.session.eligible).size!==a.session.eligible.length||!a.session.eligible.every(id=>ids.has(id))||!a.session.fresh.every(id=>a.session.eligible.includes(id))||!a.session.retries.every(r=>a.session.eligible.includes(r.entity_id)&&Number.isFinite(r.due)))return false;if(!a.session.eligible.every(id=>master.entities.find(e=>e.learningEntityId===id)?.areaId===a.snapshot.area)||!a.session.eligible.includes(a.currentID)||typeof a.solved!=='boolean')return false;return master.areas.some(e=>e.areaId===a.snapshot.area)&&['A','AB','ABC','ALL'].includes(a.snapshot.scope)&&['name','position'].includes(a.snapshot.direction)&&['10','20','all'].includes(a.snapshot.size);}catch{return false;}}
