import {normalize} from './core.js';
import {pointTolerance,unitPoint,distance,createSession,nextSession,recordSession} from './study-core.js';
export {createSession,nextSession,recordSession};
export const SCOPES={A:'まず覚える',AB:'標準',ABC:'しっかり',ALL:'すべての地点'};
export function selectedEntities(master,periodRows,area,scope){const active=new Map(periodRows.map(e=>[e.learningEntityId,e]));return master.entities.filter(e=>e.areaId===area&&(scope==='ALL'||scope.includes(e.priorityClass))).map(e=>({...active.get(e.learningEntityId),defaultPriorityClass:e.priorityClass,periodPriorityClass:active.get(e.learningEntityId).priorityClass,priorityClass:e.priorityClass}));}
export function sortEntities(rows,sort){return [...rows].sort(sort==='name'?(a,b)=>a.displayName.localeCompare(b.displayName,'ja'):sort==='frequency'?(a,b)=>(b.choiceCount??b.provisionalChoiceCount??0)-(a.choiceCount??a.provisionalChoiceCount??0)||a.displayName.localeCompare(b.displayName,'ja'):(a,b)=>(b.score??0)-(a.score??0)||a.learningEntityId.localeCompare(b.learningEntityId,'en'));}
export function drillPool(rows){return rows.filter(e=>e.learningReady&&e.coordinateConfidence==='verified_source_representative'&&Number.isFinite(e.lat)&&Number.isFinite(e.lon));}
export function viewBounds(area,entities){const xs=drillPool(entities.filter(e=>e.areaId===area.areaId));return [Math.min(area.bounds[0],...xs.map(e=>e.lon))-1,Math.min(area.bounds[1],...xs.map(e=>e.lat))-1,Math.max(area.bounds[2],...xs.map(e=>e.lon))+1,Math.max(area.bounds[3],...xs.map(e=>e.lat))+1];}
export function projector(bounds,W=960,H=720){const m=v=>Math.log(Math.tan(Math.PI/4+v*Math.PI/360)),scale=Math.min((W-52)/((bounds[2]-bounds[0])*Math.PI/180),(H-52)/(m(bounds[3])-m(bounds[1]))),w=scale*(bounds[2]-bounds[0])*Math.PI/180,h=scale*(m(bounds[3])-m(bounds[1]));return {W,H,project:([lon,lat])=>[(W-w)/2+scale*(lon-bounds[0])*Math.PI/180,(H-h)/2+scale*(m(bounds[3])-m(Math.max(-85,Math.min(85,lat))))],unproject:([x,y])=>[bounds[0]+(x-(W-w)/2)/scale*180/Math.PI,(2*Math.atan(Math.exp(m(bounds[3])-(y-(H-h)/2)/scale))-Math.PI/2)*180/Math.PI]};}
export function nameMatches(entity,text){const n=normalize(text);return !!n&&[entity.displayName,...entity.aliases].some(a=>normalize(a)===n);}
export function toleranceFor(entity,db,model,areas){if(entity.canonicalEntityIds.length===1){const profile=model.profiles.find(p=>p.entity_id===entity.canonicalEntityIds[0]);if(profile?.capability==='point')return {...pointTolerance(db,profile),bounds:db.regions.find(r=>r.id===entity.areaId).bounds,reused:true};}const adapter={entities:[{id:entity.learningEntityId,region_id:entity.areaId,entity_type:entity.entityType}],regions:[{id:entity.areaId,bounds:areas.find(a=>a.areaId===entity.areaId).bounds}],locations:[{entity_id:entity.learningEntityId,lat:entity.lat,lon:entity.lon,coordinate_status:'verified'}],occurrences:[]};return {...pointTolerance(adapter,{entity_id:entity.learningEntityId,capability:'point',exam_position_variation:'unknown'}),bounds:adapter.regions[0].bounds,reused:false};}
export function judge(entity,pt,tolerance){if(!drillPool([entity]).length)return {grade:null,accepted:false};const d=distance(unitPoint(tolerance.bounds,[entity.lon,entity.lat]),unitPoint(tolerance.bounds,pt));const grade=d<=tolerance.correct?'correct':d<=tolerance.sufficient?'sufficient':d<=tolerance.near?'near':'incorrect';return {grade,accepted:grade==='correct'||grade==='sufficient',distance:d};}
export function sessionSummary(session){const passed=new Set(session.results.filter(r=>['correct','sufficient'].includes(r.grade)).map(r=>r.entity_id)),failed=new Set(session.results.filter(r=>!['correct','sufficient'].includes(r.grade)).map(r=>r.entity_id));return {mastered:passed.size,total:session.eligible.length,answers:session.results.length,correct:session.results.filter(r=>['correct','sufficient'].includes(r.grade)).length,incorrect:session.results.filter(r=>!['correct','sufficient'].includes(r.grade)).length,retryIds:[...failed],pending:session.fresh.length+session.retries.length,remaining:session.eligible.length-passed.size};}
// Greedy label rectangles, selected first. Coordinates are rendering only, never saved as entity locations.
export function labels(points,W,H){const used=[],out=[];for(const p of points){const w=Math.min(220,[...p.name].reduce((s,c)=>s+(/[\u0000-\u007f]/.test(c)?6.5:12),0)+8),h=20;const positions=[[11,-22],[11,5],[-w-11,-22],[-w-11,5],[11,-42],[-w-11,25],[11,25]];let box=null;for(const [dx,dy]of positions){const x=Math.max(4,Math.min(W-w-4,p.x+dx)),y=Math.max(4,Math.min(H-h-4,p.y+dy));if(!used.some(b=>x<b.x+b.w+3&&x+w+3>b.x&&y<b.y+b.h+3&&y+h+3>b.y)){box={x,y,w,h};break;}}if(box){used.push(box);out.push({...p,...box});}}return out;}
