'use client';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import HoukiView from './HoukiView';
import type {TrainerMaster,LearningNote,TriviaCard} from '@/lib/houki/trainer/types';
import {loadTrainerMaster,readLocation,trainerPath,questionOrder,toggleRevealed,type TrainerLocation} from '@/lib/houki/trainer/engine';

function Sources({master,ids}:{master:TrainerMaster;ids:string[]}){return <>{ids.map(id=>{const s=master.sources.find(x=>x.id===id);return s?<p key={id}>{s.url?<a href={s.url} target="_blank" rel="noreferrer">{s.title}（一次資料・新しいタブ）</a>:s.title}{s.locatorLabel&&<small>{s.locatorLabel}</small>}{s.asOfDate&&<small>確認基準日：{s.asOfDate}</small>}</p>:<p key={id}>出典を読み込めません。</p>;})}</>;}
function Card({card,master}:{card:TriviaCard;master:TrainerMaster}){const event=master.amendments.find(a=>a.id===card.eventId);return <section className="ht-card panel"><p className="section-kicker">{card.kind==='amendment'?'改正の豆知識':'法令の落とし穴'}{master.edition==='original_sample'?' · 架空サンプル':''}</p><h3>{card.title}</h3><p>{card.text}</p>{event&&<><div className="ht-compare"><div><h4>変更前{master.edition==='original_sample'?'（架空）':''}</h4><p>{event.before}</p></div><div><h4>変更後{master.edition==='original_sample'?'（架空）':''}</h4><p>{event.after}</p></div></div><p>{event.change}</p><p>公布日：{event.promulgatedAt??'設定なし'} / 施行日：{event.effectiveAt??'設定なし'}</p><p>理由：{event.reason??'未確認・設定なし'}</p><ul>{event.unknowns.map(x=><li key={x}>{x}</li>)}</ul></>}<details><summary>出典を見る</summary><Sources master={master} ids={card.sourceIds}/></details></section>;}
function Note({note,master,openQuestion}:{note:LearningNote;master:TrainerMaster;openQuestion:(id:string)=>void}){return <article className="ht-lesson panel"><h2 tabIndex={-1} data-trainer-focus>{note.title}</h2><section><h3>このテーマで覚えること</h3><p className="ht-goal">{note.goal}</p></section><section><h3>要点の解説</h3><p>{note.explanation}</p></section><section><h3>条件・例外</h3>{note.ruleIds.map(id=>{const r=master.rules.find(x=>x.id===id);return r&&<div key={id}><p><strong>主体：</strong>{r.subject}</p><p><strong>行為：</strong>{r.action}</p>{r.conditionIds.map(cid=>{const c=master.conditions.find(x=>x.id===cid);return c&&<div key={cid}><p><strong>{c.operator==='AND'?'両方必要（AND）':'いずれかでよい（OR）'}</strong></p><ul>{c.requirements.map(x=><li key={x}>{x}</li>)}</ul><p>例外：{c.exceptions.join(' / ')||'この架空ルールに設定なし'}</p></div>;})}</div>;})}</section><section><h3>手順で確かめる</h3><ol>{note.steps.map(x=><li key={x}>{x}</li>)}</ol></section><section><h3>確認問題</h3><p>答えを隠して確認し、問題画面で解説を開けます。</p><div className="ht-actions">{note.questionIds.map(id=><button className="btn btn-primary" key={id} onClick={()=>openQuestion(id)}>{master.questions.find(q=>q.id===id)?.title??'問題を確認'}</button>)}</div></section>{note.cardIds.map(id=>{const c=master.cards.find(x=>x.id===id);return c&&<Card card={c} master={master} key={id}/>;})}<details className="ht-audit"><summary>出典・確認範囲・未確認事項</summary><p>確認範囲：{note.scope}</p><p>法令確認基準日：{note.asOfDate??'対象外（架空サンプル）'}</p><p>法令本文の引用ではありません。</p><ul>{note.unknowns.map(x=><li key={x}>{x}</li>)}</ul><Sources master={master} ids={note.sourceIds}/></details></article>;}
export default function HoukiTrainerView({onBack}:{onBack:()=>void}){
 const [master,setMaster]=useState<TrainerMaster>();const [error,setError]=useState('');
 const [loc,setLoc]=useState<TrainerLocation>(()=>readLocation(''));const [revealed,setRevealed]=useState<string[]>([]);const main=useRef<HTMLDivElement>(null);const focusNext=useRef(false);
 useEffect(()=>{setLoc(readLocation(window.location.search));const onPop=()=>{focusNext.current=true;setLoc(readLocation(window.location.search));};window.addEventListener('popstate',onPop);let active=true;loadTrainerMaster().then(x=>{if(active)setMaster(x);}).catch(()=>{if(active)setError('教材を読み込めません。再読み込みするか、既存28句を開いてください。');});return()=>{active=false;window.removeEventListener('popstate',onPop);};},[]);
 const order=useMemo(()=>master?questionOrder(master.questions,loc.year,loc.chapter,loc.random,loc.seed):[],[master,loc.year,loc.chapter,loc.random,loc.seed]);
 const question=order.find(q=>q.id===loc.question)??(!loc.question?order[0]:undefined);const note=master?.notes.find(n=>n.id===loc.theme);
 useLayoutEffect(()=>{setRevealed([]);if(focusNext.current){(main.current?.querySelector<HTMLElement>('[data-trainer-focus]')??main.current?.querySelector<HTMLElement>('h1'))?.focus();focusNext.current=false;}},[loc,question?.id]);
 function go(patch:Partial<TrainerLocation>){const next={...loc,...patch};if(next.mode!=='sheet')next.question='';window.history.pushState(null,'',trainerPath(next));focusNext.current=true;setLoc(next);}
 function openQuestion(id:string){go({mode:'sheet',theme:'',question:id,chapter:'all',year:'all',random:false});}
 if(loc.mode==='legacy')return <><div className="page-pad ht-legacy-back"><button className="btn btn-secondary" onClick={()=>go({mode:'home'})}>← 法規トレーナーへ</button></div><HoukiView onBack={onBack}/></>;
 const sample=master?.edition==='original_sample';const index=question?order.indexOf(question):-1;
 return <section className="ht-trainer page-pad" ref={main}><header className="ht-heading"><div><p className="section-kicker">一総通 · 法規</p><h1 tabIndex={-1}>法規トレーナー</h1><p>参考書で理解し、赤シートで確かめる。</p></div><button className="btn btn-secondary" onClick={onBack}>一総通へ戻る</button></header>
 {sample&&<p className="ht-notice">新しい2モードは、架空ルールのオリジナルサンプルです。実試験問題・法令教材ではありません。法規の学習には「既存28句」を利用できます。</p>}
 {loc.mode!=='home'&&<button className="btn btn-secondary ht-back" onClick={()=>go({mode:'home',theme:''})}>← 法規トレーナーの入口</button>}
 {error&&<div role="alert"><p>{error}</p><button className="btn btn-secondary" onClick={()=>window.location.reload()}>再読み込み</button></div>}
 {!master&&!error&&<p role="status">教材を読み込んでいます…</p>}
 {loc.mode==='home'&&<><div className="ht-entrances"><button className="panel" onClick={()=>go({mode:'book',theme:''})}><span className="section-kicker">READ</span><h2>参考書で学ぶ</h2><p>要点 → 条件・例外 → 確認問題</p><small>{master?.notes.length??0}テーマ{sample?'（架空サンプル）':''}</small></button><button className="panel" onClick={()=>go({mode:'sheet',question:''})}><span className="section-kicker">REPEAT</span><h2>赤シートで特訓</h2><p>答えを隠し、1問ずつ繰り返す</p><small>{master?.questions.length??0}問{sample?'（オリジナルサンプル）':''}</small></button></div><section className="ht-existing panel"><h2>法規の既存28句</h2><p>これまでの確認済み教材と25点セット。学習記録・途中のセットはそのままです。</p><button className="btn btn-secondary" onClick={()=>go({mode:'legacy'})}>既存28句・25点セットを開く</button></section></>}
 {master&&loc.mode==='book'&&(!loc.theme?<><h2 tabIndex={-1}>章から選ぶ</h2>{master.chapters.map(c=><section className="ht-chapter panel" key={c.id}><h3>{c.title}{sample?'（架空）':''}</h3>{master.notes.filter(n=>n.chapterId===c.id).map(n=><button className="ht-theme" key={n.id} onClick={()=>go({theme:n.id})}><strong>{n.title}</strong><span>{n.goal}</span></button>)}</section>)}<p className="ht-muted">実法令の参考書は未投入です。未完成の章を利用可能件数には含めていません。</p></>:note?<><button className="btn btn-secondary ht-back" onClick={()=>go({theme:''})}>← 章一覧へ</button><Note note={note} master={master} openQuestion={openQuestion}/></>:<p role="alert">このテーマは見つかりません。章一覧から選び直してください。</p>)}
 {master&&loc.mode==='sheet'&&<><h2 tabIndex={-1}>赤シートで特訓</h2><div className="ht-filters"><label>年度{sample?'（サンプル作成年）':''}<select value={loc.year} onChange={e=>go({year:e.target.value,question:''})}><option value="all">すべて</option>{[...new Set(master.questions.map(q=>q.historicalRef?.examDate.slice(0,4)??q.sampleYear).filter((x):x is string=>!!x))].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label><label>分野<select value={loc.chapter} onChange={e=>go({chapter:e.target.value,question:''})}><option value="all">すべて</option>{master.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button className="btn btn-secondary" aria-pressed={loc.random} onClick={()=>go({random:!loc.random,seed:Date.now()>>>0,question:''})}>{loc.random?'順番に戻す':'ランダム出題'}</button></div>
 {!order.length?<p role="status">この条件に合う問題はありません。年度・分野を変更してください。</p>:!question?<p role="alert">指定した問題は見つかりません。フィルターを選び直してください。</p>:<article className="ht-sheet panel" key={question.id}><p className="section-kicker">{index+1} / {order.length} · {question.provenance==='original_sample'?'実試験ではないオリジナルサンプル':`${question.historicalRef?.examDate} ${question.historicalRef?.questionNumber}`}</p><h3 tabIndex={-1} data-trainer-focus>{question.title}</h3><p className="ht-muted">{question.historicalRef?'当時の公式正答。現行法への置換はしていません。':`作成年：${question.sampleYear} / 試験年月・問題番号：対象外`}</p><p className="ht-notice">{question.relationToCurrent}</p><p className="ht-question">{question.tokens.map((t,i)=>t.kind==='text'?<span key={i}>{t.text}</span>:(()=>{const b=question.blanks.find(x=>x.id===t.blankId)!;const shown=revealed.includes(b.printedPositionId);return <button key={b.printedPositionId} className="ht-blank" aria-expanded={shown} aria-label={`穴${b.slotLabel}：${shown?'答えを隠す':'答えを表示'}`} onClick={()=>setRevealed(ids=>toggleRevealed(ids,b.printedPositionId))}>穴{b.slotLabel}：{shown?b.answer:'答えを表示'}</button>;})())}</p><div className="ht-actions"><button className="btn btn-secondary" onClick={()=>setRevealed(question.blanks.map(b=>b.printedPositionId))}>すべて表示</button><button className="btn btn-secondary" onClick={()=>setRevealed([])}>すべて隠す</button></div><p role="status" aria-live="polite">{revealed.length} / {question.blanks.length}個の答えを表示中</p><details key={question.id}><summary>解説を読む</summary><p>{question.explanation}</p></details><div className="ht-actions"><button className="btn btn-secondary" disabled={index<=0} onClick={()=>go({question:order[index-1].id})}>前の問題</button><button className="btn btn-primary" disabled={index>=order.length-1} onClick={()=>go({question:order[index+1].id})}>次の問題</button><button className="btn btn-secondary" onClick={()=>go({mode:'book',theme:question.themeId})}>対応する参考書へ</button></div></article>}</>}
 </section>;
}
