'use client';
import {useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import HoukiView from './HoukiView';
import type {TrainerMaster} from '@/lib/houki/trainer/types';
import {readLocation,trainerPath,questionOrder,type TrainerLocation} from '@/lib/houki/trainer/engine';

import {loadDevReview} from '@/lib/houki/trainer/review-loader';
import {loadLessonRelease} from '@/lib/houki/trainer/lesson-loader';
import type {LessonRelease} from '@/lib/houki/trainer/lesson-types';
import {LessonPlayer,RedSheetPlayer} from '@/app/components/houki/LessonPlayer';
import {encodeSheetReturn,decodeSheetReturn,restoredPositions,type SheetReturn} from '@/lib/houki/trainer/return-state';
export default function HoukiTrainerView({onBack,onOpenKakomon}:{onBack:()=>void;onOpenKakomon?:()=>void}){
 const [master,setMaster]=useState<TrainerMaster>();const [release,setRelease]=useState<LessonRelease>();const [sheetReturn,setSheetReturn]=useState<SheetReturn|null>(null);const pendingRestore=useRef<SheetReturn|null>(null);const [explanationOpen,setExplanationOpen]=useState(false);const [error,setError]=useState('');
 const [loc,setLoc]=useState<TrainerLocation>(()=>readLocation(''));const [revealed,setRevealed]=useState<string[]>([]);const main=useRef<HTMLDivElement>(null);const focusNext=useRef(false);
 useEffect(()=>{setLoc(readLocation(window.location.search));setSheetReturn(decodeSheetReturn(new URLSearchParams(window.location.search).get('returnSheet')));const onPop=()=>{focusNext.current=true;const back=decodeSheetReturn(new URLSearchParams(window.location.search).get('returnSheet'));setSheetReturn(back);pendingRestore.current=window.history.state?.sheetState??null;setLoc(readLocation(window.location.search));};window.addEventListener('popstate',onPop);let active=true;const review=process.env.NODE_ENV==='development'&&new URLSearchParams(window.location.search).get('review')==='1';(review?loadDevReview():loadLessonRelease()).then(x=>{if(active){setRelease(x);setMaster(x.master);}}).catch(()=>{if(active)setError('教材を読み込めません。再読み込みするか、既存28句を開いてください。');});return()=>{active=false;window.removeEventListener('popstate',onPop);};},[]);
 const order=useMemo(()=>master?questionOrder(master.questions,loc.year,loc.chapter,loc.random,loc.seed):[],[master,loc.year,loc.chapter,loc.random,loc.seed]);
 const question=order.find(q=>q.id===loc.question)??(!loc.question?order[0]:undefined);const note=master?.notes.find(n=>n.id===loc.theme);
 useLayoutEffect(()=>{const restored=pendingRestore.current;if(restored&&question){setRevealed(restoredPositions(restored,question));setExplanationOpen(restored.questionVersion===question.version&&restored.explanationOpen);pendingRestore.current=null;}else{setRevealed([]);setExplanationOpen(false);}if(focusNext.current){const target=main.current?.querySelector<HTMLElement>('[data-trainer-focus]')??main.current?.querySelector<HTMLElement>('h1');target?.focus({preventScroll:true});target?.scrollIntoView({block:'start',behavior:'instant'});focusNext.current=false;}},[loc,question?.id]);
 function go(patch:Partial<TrainerLocation>,returnState:SheetReturn|null=null){const next={...loc,...patch};if(next.mode!=='sheet')next.question='';const state=question?{location:{...loc,question:question.id},questionVersion:question.version,revealed,explanationOpen}:null;window.history.replaceState({sheetState:loc.mode==='sheet'?state:window.history.state?.sheetState},'',window.location.href);const url=trainerPath(next)+(master?.edition==='internal_review'?'&review=1':'')+(returnState?'&returnSheet='+encodeURIComponent(encodeSheetReturn(returnState)):'');window.history.pushState({sheetState:next.mode==='sheet'?pendingRestore.current:null},'',url);setSheetReturn(returnState);focusNext.current=true;setLoc(next);}
 function openQuestion(id:string){go({mode:'sheet',theme:'',question:id,chapter:'all',year:'all',random:false});}
 if(loc.mode==='legacy')return <><div className="page-pad ht-legacy-back"><button className="btn btn-secondary" onClick={()=>go({mode:'home'})}>← 法規トレーナーへ</button></div><HoukiView onBack={onBack}/></>;
 const sample=master?.edition==='original_sample';const index=question?order.indexOf(question):-1;
 return <section className="ht-trainer page-pad" ref={main}><header className="ht-heading"><div><p className="section-kicker">一総通 · 法規</p><h1 tabIndex={-1}>法規トレーナー</h1><p>参考書で理解し、赤シートで確かめる。</p></div><button className="btn btn-secondary" onClick={onBack}>一総通へ戻る</button></header>
 {process.env.NODE_ENV==='development'&&<a className="btn btn-secondary" href="/__houki-review/login">内部教材レビュー（担当者認証）</a>}
 {master?.edition==='internal_review'&&<button className="btn btn-secondary" onClick={async()=>{await fetch('/__houki-review/logout',{method:'POST',credentials:'same-origin'});window.location.assign('/app/houki');}}>レビューを終了・通常教材へ</button>}
 {master?.edition==='internal_review'&&<p className="ht-notice">実法規・内部レビュー専用／一般公開未承認。教材版 {release?.contentVersion} · 法令確認基準日 {release?.dates.verificationAsOf}。権利審査・人間による公開承認は未完了です。</p>}
 {master?.edition==='approved_release'&&<p className="ht-notice">法令確認基準日：2026年10月7日。一総通法規の限定範囲を扱う、CWOT独自編集教材です。政府機関・試験実施機関の公式教材ではありません。練習問題は独自作成で、過去問の転載ではありません。最新法令は各テーマの公式資料で確認してください。リンク先の現在の版は、この教材の確認版と異なる場合があります。</p>}
 {sample&&<p className="ht-notice">新しい2モードは、架空ルールのオリジナルサンプルです。実試験問題・法令教材ではありません。法規の学習には「既存28句」を利用できます。</p>}
 {loc.mode!=='home'&&<button className="btn btn-secondary ht-back" onClick={()=>go({mode:'home',theme:''})}>← 法規トレーナーの入口</button>}
 {error&&<div role="alert"><p>{error}</p><button className="btn btn-secondary" onClick={()=>window.location.reload()}>再読み込み</button></div>}
 {!master&&!error&&<p role="status">教材を読み込んでいます…</p>}
 {loc.mode==='home'&&<><div className="ht-entrances"><button className="panel" onClick={()=>go({mode:'book',theme:''})}><span className="section-kicker">READ</span><h2>参考書で学ぶ</h2><p>要点 → 条件・例外 → 確認問題</p><small>{master?.notes.length??0}テーマ{sample?'（架空サンプル）':''}</small></button><button className="panel" onClick={()=>go({mode:'sheet',question:''})}><span className="section-kicker">REPEAT</span><h2>赤シートで特訓</h2><p>答えを隠し、1問ずつ繰り返す</p><small>{master?.questions.length??0}問{sample?'（オリジナルサンプル）':''}</small></button>{onOpenKakomon&&<button className="panel" onClick={onOpenKakomon}><span className="section-kicker">PAST EXAMS</span><h2>過去問を周回</h2><p>本番の問題を1周ずつ解き、正解でランクを上げる</p><small>平成23年〜令和8年・出題当時の正答</small></button>}</div><section className="ht-existing panel"><h2>法規の既存28句</h2><p>これまでの確認済み教材と25点セット。学習記録・途中のセットはそのままです。</p><button className="btn btn-secondary" onClick={()=>go({mode:'legacy'})}>既存28句・25点セットを開く</button></section></>}
 {master&&loc.mode==='book'&&(!loc.theme?<><h2 tabIndex={-1}>章から選ぶ</h2>{master.chapters.map(c=><section className="ht-chapter panel" key={c.id}><h3>{c.title}{sample?'（架空）':''}</h3>{master.notes.filter(n=>n.chapterId===c.id).map(n=><button className="ht-theme" key={n.id} onClick={()=>go({theme:n.id})}><strong>{n.title}</strong><span>{n.goal}</span></button>)}</section>)}<p className="ht-muted">{master.edition==='internal_review'?'確認済みscopeに限る内部教材です。出典・確認版・未確認事項は各テーマで確認できます。':master.edition==='approved_release'?'確認済みの限定範囲を学べます。出典・確認版・未確認事項は各テーマで確認できます。':'実法令の参考書は未投入です。未完成の章を利用可能件数には含めていません。'}</p></>:note?<><button className="btn btn-secondary ht-back" onClick={()=>go({theme:''})}>← 章一覧へ</button>{sheetReturn&&<button className="btn btn-primary ht-back" onClick={()=>{pendingRestore.current=sheetReturn;go(sheetReturn.location);}}>← 元の赤シートへ戻る</button>}{release&&<LessonPlayer release={release} lessonId={note.id} openQuestion={openQuestion}/>}</>:<p role="alert">このテーマは見つかりません。章一覧から選び直してください。</p>)}
 {master&&loc.mode==='sheet'&&<><h2 tabIndex={-1}>赤シートで特訓</h2><div className="ht-filters"><label>年度{sample?'（サンプル作成年）':''}<select value={loc.year} onChange={e=>go({year:e.target.value,question:''})}><option value="all">すべて</option>{[...new Set(master.questions.map(q=>q.historicalRef?.examDate.slice(0,4)??q.sampleYear).filter((x):x is string=>!!x))].sort().reverse().map(y=><option key={y}>{y}</option>)}</select></label><label>分野<select value={loc.chapter} onChange={e=>go({chapter:e.target.value,question:''})}><option value="all">すべて</option>{master.chapters.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><button className="btn btn-secondary" aria-pressed={loc.random} onClick={()=>go({random:!loc.random,seed:Date.now()>>>0,question:''})}>{loc.random?'順番に戻す':'ランダム出題'}</button></div>
 {!order.length?<p role="status">この条件に合う問題はありません。年度・分野を変更してください。</p>:!question?<p role="alert">指定した問題は見つかりません。フィルターを選び直してください。</p>:<article className="ht-sheet panel" key={question.id}><p className="section-kicker">{index+1} / {order.length} · {question.provenance==='original_practice'?'独自作成の練習問題（過去問ではありません）':question.provenance==='original_sample'?'実試験ではないオリジナルサンプル':`${question.historicalRef?.examDate} ${question.historicalRef?.questionNumber}`}</p><h3 tabIndex={-1} data-trainer-focus>{question.title}</h3><p className="ht-muted">{question.historicalRef?'当時の公式正答。現行法への置換はしていません。':question.provenance==='original_practice'?'独自練習：試験年月・問題番号はありません。':`作成年：${question.sampleYear} / 試験年月・問題番号：対象外`}</p><p className="ht-notice">{question.relationToCurrent}</p><RedSheetPlayer question={question} revealed={revealed} setRevealed={setRevealed} explanationOpen={explanationOpen} setExplanationOpen={setExplanationOpen}/><div className="ht-actions"><button className="btn btn-secondary" disabled={index<=0} onClick={()=>go({question:order[index-1].id})}>前の問題</button><button className="btn btn-primary" disabled={index>=order.length-1} onClick={()=>go({question:order[index+1].id})}>次の問題</button><button className="btn btn-secondary" onClick={()=>go({mode:'book',theme:question.themeId},{location:{...loc,question:question.id},questionVersion:question.version,revealed,explanationOpen})}>対応する参考書へ</button></div></article>}</>}
 </section>;
}
