from pathlib import Path
import json
p=Path(__file__).resolve().parent.parent
rows=json.loads((p/'english_illustration_selection.json').read_text());by={}
for r in rows:
 if r['decision']=='A':by.setdefault(r['candidateAssetId'],[]).append(r)
style='Use case: scientific-educational. A single wide 3:2 landscape scene-based educational editorial illustration for an adult specialist English learning card. Simplified painted scene, moderate dimensionality, clean silhouettes, restrained detail, calm professional tone. Muted navy, natural blue and blue-gray, off-white, limited warm amber accent. Like a simplified maritime editorial scene, neither photorealistic nor an icon/diagram/comic. Important teaching subject near the center, readable at about 320px display width; small mechanical details are not the teaching point. Absolutely no text, words, letters, numbers, labels, logos, watermarks, legends, UI, panels or split-screen. One clear learning point, no unrelated decorative objects.'
scene={
'shore-ship-radio':'A low coastal radio-station building with a modest slender vertical radio antenna mast stands on a shore at the left. ONE merchant vessel with its own modest radio aerial is on the sea at the right. Both are large and clearly legible; a single subtle warm dashed TWO-WAY curved communication arc connects the shore mast and vessel aerial. No satellite dish anywhere, no radar dishes, no rescue scene, no additional boats. The only teaching point is the shore-to-ship relationship. Do not turn the land building into a control tower. Keep sea and shoreline simple.',
'air-ground-radio':'ONE aircraft flying low enough to be clearly seen above a simple airfield, and a small ground radio-station building with a vertical radio mast. A subtle warm dashed two-way radio arc connects the aircraft and the ground mast. Teaching point: airborne radio station versus ground radio station. Do NOT make a prominent ATC control tower; this is a generic ground aviation radio station, not a statement that every aeronautical station is an ATC tower. No satellites, radar dish, runway markings, lettering or additional aircraft.',
'person-overboard':'View from outside a merchant vessel close to its side: ONE fully clothed adult crew member is in the water just outside the ship side, their head and shoulders visibly above the water, alert and not injured. The ship rail and hull clearly establish that the person is outside the vessel and in the sea. Calm non-graphic instructional depiction of a person overboard, not a swimming holiday. No blood, dramatic injuries, rescue procedures, lifejacket lesson, other people, splashes hiding the person, text or rescue-boat subplot.',
'ship-aground':'A medium-sized cargo vessel sits motionless on a sandy shoal, in a simplified partly transparent shallow-water scene allowing the bottom of the hull visibly to rest directly on the sandy seabed. The main teaching point is hull touching the bottom, not anchored waiting. Gentle sea, believable grounded hull, no rocks piercing the deck, no chains or anchor, no rescue boats, no flames, no dramatic wreck.',
'boat-capsized':'ONE small unoccupied boat is visibly overturned in the sea, its bottom exposed above the water and its open deck facing down. It is genuinely capsized, not just leaning or rolling. Simplified quiet instructional sea scene, no people or casualties, no injuries, no storm drama or extra vessels. The upturned hull is large and central.',
'flooded-engine-room':'Inside a simplified cargo-ship engine room, seawater has flooded the LOWER part of the room around the lower bases of simple fixed machinery and a low platform. The machinery stays anchored in place; the upper parts remain above the rising water. It must unmistakably be water INSIDE a ship compartment, not outside waves. No people, labels, electrical sparks, complex invented piping, or assertion that every flooded room means the entire vessel sinks. One clear scene, not a technical cutaway diagram.',
'ship-at-berth':'A modest merchant vessel lies alongside a quay at its clearly defined berthing place. Oblique view shows the boat side next to the quay, fenders between ship and quay, a few unobtrusive mooring lines connecting to shore. No line count or rope configuration is presented as a rule: the main teaching point is the vessel alongside its quay position, contrasted with open-water anchorage. No labels, other ships, cranes becoming the main subject, people, or intricate knot tutorial.',
'ship-at-anchorage':'ONE merchant vessel waits in sheltered open water outside a distant harbour shore. A single anchor chain visibly leads down from the bow into the water. It is away from any quay, not alongside land. The main point is the open-water place where the vessel is anchored; do not illustrate anchor mechanics, underwater installation details, sailing movement, other ships, port icons or written labels.',
'under-keel-gap':'A simple calm coastal scene with a central merchant vessel on water. An illustrative clear-water section lets the viewer see the hull below the waterline and the sandy seabed below it. Show a small but unmistakable WATER GAP BETWEEN THE LOWEST HULL/KEEL AND THE SEABED. The hull does NOT touch bottom. Sea surface line, hull bottom and seabed must remain distinct at small size. No measurement numerals, dimensions, arrows, labels, technical engineering diagram, bridge, coral or distracting objects. The gap, not total water depth, is the teaching point.',
'ship-height-below-bridge':'A single moderate cargo vessel passing under a plain bridge over a calm waterway, viewed from the side. The entire ship from waterline to highest mast top is visible, with comfortable clear space ABOVE the mast and BELOW the bridge underside. Add ONLY ONE subtle unlabelled amber vertical height bracket beside the vessel spanning FROM THE WATER SURFACE TO THE TOP OF THE HIGHEST SHIP MAST; it must stop at the ship mast top, NOT extend to the bridge. No second bracket, labels or numbers. Teaching point is ship height above water; bridge merely provides context. No vehicles, people, impossibly crossing pylons, or hull-to-seabed dimension.',
'fog-at-harbour':'View from a ship towards a harbour entrance in thick natural sea fog. The nearby bow edge is crisp and dark, while a harbour breakwater and coastal silhouettes quickly disappear into dense pale blue-gray fog ahead. The fog is a visible low layer obscuring landmarks, NOT smoke, rain, overcast skies alone, or a white blank image. No crash, rescue, other ships, written signs, numbers or instruments. Large simple near/far shapes make the obscured visibility apparent at small size.',
'rope-fouled-propeller':'Underwater close scene at the STERN of a simple merchant hull: a believable bronze marine propeller on a horizontal shaft is visibly fouled by a rope wrapped around the shaft and caught between the propeller blades. The teaching point is ROPE ENTANGLEMENT, not dirt or corrosion. Large propeller and clearly visible rope, gentle blue water, no bubbles hiding the problem, no divers, cutting tools, precise engineering annotations or above-water propeller. Do not make it an aircraft turbine.',
'ship-rolling':'ONE upright merchant vessel seen almost straight from its BOW, tilted modestly to its port or starboard side as it rolls on gentle waves. Its transverse lean is clearly visible but it is far from capsizing. ONE restrained amber double-ended curved motion arrow around the front silhouette indicates side-to-side rolling ACROSS THE SHIP WIDTH. No fore-aft arrow, duplicated/ghost ships, labels, diagrams or storm catastrophe. This bow-on viewpoint must make rolling distinct from side-profile pitching.',
'ship-pitching':'ONE merchant vessel shown in full SIDE PROFILE on sea swells, with its BOW RISING and STERN LOWER, while still floating with a substantial part of its hull in the water. ONE restrained amber double-ended curved motion arrow near the bow indicates up-and-down PITCHING of the bow and stern. No transverse side-lean, no bow-on view, ghost boats, captions, labels, airborne boat or capsizing. The side view and opposite bow/stern heights must distinguish this image from rolling.',
'ship-bridge':'A simplified scene INSIDE the elevated NAVIGATION BRIDGE of a merchant vessel. Broad forward-facing windows show sea and a small part of the foredeck ahead; a simple helm console and wheel are central. The room is the control place aboard ship. No road bridge, suspension bridge, aircraft cockpit, radio-operator portrait, detailed screen text, labels, dense control panels or invented technical procedure. Clean readable room silhouette and forward view.',
'bulbous-bow':'Close oblique SIDE VIEW of the BOW of a large merchant vessel. A simplified clear-water view reveals the ROUND BULBOUS PROJECTION at the front of the hull JUST BELOW THE WATERLINE. Show unmistakable rounded protruding bulb pointing forward, attached to the bow under the forward stem; not a propeller and not at the stern. Hull in muted navy above water and warm muted red-gray below, blue water. No structural exploded diagram, labels, arrows, speed claims, waves-as-physics diagram, or entire ship that makes the bulb tiny.'
}
assert by.keys()==scene.keys()
out=[]
for id,items in by.items():
 # The full edited learner text is an input; audit text is deliberately excluded.
 context=[{'term':i['term'],**i['learnerSource'],'scene_titles':[g['title'] for g in json.loads((p/'english_master_E2_0_1_baseline.json').read_text())['groups'] if g['id'] in i['learnerSource']['learning_groups']]} for i in items]
 prompt=style+'\nPrimary scene: '+scene[id]+'\nEdited learner context (for meaning only, NEVER render this text): '+json.dumps(context,ensure_ascii=False)+'\nLearning point: '+' / '.join(i['learningPoint'] for i in items)+'\nSemantic risks to avoid: '+' / '.join(i['risk'] for i in items)
 out.append({'assetId':id,'learningEntityIds':[i['learningEntityId'] for i in items],'prompt':prompt,'status':'not_generated'})
(p/'generation_prompts.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print('prompts',len(out))
